### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-openapi-generator#22]
* [x] Rebranding branch created
  * [x] New design applied (font, logos, colors)
  * [x] Codename references renamed
  * [x] Ticker references renamed
  * [x] Links reviewed
  * [x] README reviewed
  * [x] Dependencies reviewed
  * [x] PR created
  * [x] Package renamed
  * [x] Package deployed

**Comment by fboucquez** [comment]
Related https://github.com/nemtech/nem2-sdk-java/issues/228
